"""add role to users table

Revision ID: ebf916b9ce1d
Revises: 504aac612fb0
Create Date: 2025-04-19 20:35:20.272339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebf916b9ce1d'
down_revision: Union[str, None] = '504aac612fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    op.alter_column('user_accounts', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_accounts', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.alter_column('user_accounts', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_accounts', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_accounts', 'role')
    # ### end Alembic commands ###
